version: "3.9"

# Services
services:
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.17.0
    volumes:
      - ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
      - "9300:9300:
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    cap_add:
      - IPC_LOCK
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  kibana:
    container_name: kibana
    image: kibana:7.17.0
    volumes:
      - ./config/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  iglu-server:
    container_name: iglu-server
    image: snowplow/iglu-server:latest
    ports:
      - "8081:8081"
    volumes:
      - ./config:/snowplow/config
    command: --config /snowplow/config/iglu-server.hocon

  iglu:
    container_name: iglu
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./iglu:/usr/share/nginx/html:ro
    command: /bin/bash -c "echo 'autoindex on;' > /etc/nginx/conf.d/autoindex.conf && nginx -g 'daemon off;'"


  nsqlookupd:
    container_name: nsqlookupd
    image: nsqio/nsq:v1.2.1
    command: /nsqlookupd
    ports:
      - "4160:4160"
      - "4161:4161"

  nsqd:
    container_name: nsqd
    image: nsqio/nsq:v1.2.1
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160
    depends_on:
      - nsqlookupd
    ports:
      - "4150:4150"
      - "4151:4151"

  nsqadmin:
    container_name: nsqadmin
    image: nsqio/nsq:v1.2.1
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    depends_on:
      - nsqlookupd
    ports:
      - "4171:4171"

  stream-collector:
    container_name: stream-collector
    image: snowplow/scala-stream-collector-nsq:2.5.0-jre17
    command: [ "--config", "/snowplow/config/stream-collector.hocon" ]
    depends_on:
      - nsqd
    ports:
      - "8080:8080"
    volumes:
      - ./config:/snowplow/config
    environment:
      - "SP_JAVA_OPTS=-Xms256m -Xmx256m"

  stream-enrich:
    container_name: stream-enrich
    image: snowplow/stream-enrich-nsq:2.0.7
    command: [
      "--config", "/snowplow/config/stream-enrich.hocon",
      "--resolver", "file:/snowplow/config/resolver.json",
      "--enrichments", "file:/snowplow/config/enrichments",
      "--force-cached-files-download",
    ]
    depends_on:
      - stream-collector
    links:
      - iglu
    volumes:
      - ./config:/snowplow/config
    environment:
      - "SP_JAVA_OPTS=-Xms256m -Xmx256m"

  elasticsearch-loader-good:
    container_name: elasticsearch-loader-good
    image: snowplow/elasticsearch-loader:2.0.4
    depends_on:
      - stream-collector
      - elasticsearch
    volumes:
      - ./config:/snowplow/config
    environment:
      - "SP_JAVA_OPTS=-Xms256m -Xmx256m"
    command: [
      "--config", "/snowplow/config/elasticsearch-loader-good.hocon"
    ]

  elasticsearch-loader-bad:
    container_name: elasticsearch-loader-bad
    image: snowplow/elasticsearch-loader:2.0.4
    depends_on:
      - stream-collector
      - elasticsearch
    volumes:
      - ./config:/snowplow/config
    environment:
      - "SP_JAVA_OPTS=-Xms256m -Xmx256m"
    command: ["--config", "/snowplow/config/elasticsearch-loader-bad.hocon"]

  setup:
    container_name: setup
    image: alpine:latest
    command: /bin/sh -c "
        apk --no-cache add curl
        && curl -sS -X POST http://nsqd:4151/topic/create?topic=raw
        && curl -sS -X POST http://nsqd:4151/topic/create?topic=enriched
        && curl -sS -X POST http://nsqd:4151/topic/create?topic=bad
      "
    depends_on:
      - nsqlookupd
